### ISSUE TITLE
Nuke module not working on Firefox

### ISSUE THREAD

**Issue by rasher** [creesch/reddit-moderator-toolbox#488] opened 2015-03-29 20:33 UTC
There may be more to this, but the only thing I've been able to figure out is that it seems to be broken for me and another guy on Firefox.

I get an unhelpful error in the Console saying "[object Object]" in "sandbox.js (line 304)" - once per comment to remove - and then all it does it show the loading-graphic and count comments in the progress window. No net traffic occurs during this time. It also doesn't go "out of" the progress mode. I.e. when I navigate away from the page it asks me to confirm.

Comments are not removed.

**Comment by creesch** [comment] 2015-03-30 07:37
One of the reasons that module is still in beta, there are more issues that need to be resolved before we can upgrade it to stable.

**Comment by agentlame** [comment] 2015-03-31 15:32
This is a dupe of #430, more or less.

**Closed by agentlame** 2015-03-31 15:32 UTC

**Comment by creesch** [comment] 2015-03-31 18:10
So it is.
