### ISSUE TITLE
Modules occasionally run multiple times

### ISSUE THREAD

**Issue by TheEnigmaBlade** [creesch/reddit-moderator-toolbox#499] opened 2015-04-27 23:05 UTC
This occasionally happens to me in Firefox, but a fellow mod has it happening most every time in Chrome. For example:

![](http://i.imgur.com/Mk7rPRx.png)

![](http://i.imgur.com/WguwfYn.png)

**Comment by creesch** [comment] 2015-04-28 07:00
Hrm, first time I am seeing that issue, I wonder if it is firefox specific.

**Comment by agentlame** [comment] 2015-04-28 15:47
The init process is extremely well logged.  Can you have them enable debug and copy their log?

**Comment by creesch** [comment] 2015-05-01 07:24
@TheEnigmaBlade are you sure you don't have two versions of toolbox running somehow?  It looks really similar to what happens when I have toolbox from the chrome store and the dev version enabled.

**Comment by agentlame** [comment] 2015-05-04 15:55
Dude, @TheEnigmaBlade can you pretty please give us an update on this?

**Comment by TheEnigmaBlade** [comment] 2015-05-05 04:06
The mod having those issues (screenshots aren't mine) aren't around right now, so I can't ask. Might be best to assume it's more of a local issue since I can't manually reproduce it.

**Comment by agentlame** [comment] 2015-05-05 04:14
Since we only have a single source for this issue I'm deferring it to another release.

**Comment by Garethp** [comment] 2015-05-06 23:49
I got this issue this morning. Came here to read the comment, and it was two versions of reddit toolbox enabled at the same time. Just weighing in here

**Comment by agentlame** [comment] 2015-05-06 23:52
SOMEONE POST THEIR DAMNED DEBUG LOG.

**Comment by Garethp** [comment] 2015-05-06 23:53
I mean... do you want me to re-enable the second version of reddit toolbox and grab a debug log from it? It worked fine when I disabled my second version

**Comment by agentlame** [comment] 2015-05-07 00:17
@Garethp Oops, I misread.  I thought you were confirming the issue.

**Comment by agentlame** [comment] 2015-07-06 16:06
Closing this... it has never been confirmed.  Re-open it or make a new issue once it is.

**Closed by agentlame** 2015-07-06 16:06 UTC
Labels: bug, can't reproduce, module: all
